### ISSUE TITLE
UI changes for Login Screen Fragment

### ISSUE THREAD

**Issue by harshitkeshrihk** [DSC-JSS-NOIDA/RapidHire#1]
![Screenshot 2022-10-01 131235](https://user-images.githubusercontent.com/85623292/193398843-5dd1f014-a584-41d2-874e-1553cfe614a2.png)

**Comment by nandinivats30** [comment]
Please assign me this issue.

**Comment by nandinivats30** [comment]
Issue resolved, please review.
