### ISSUE TITLE
UI changes for splash Screen Activity and add fade animation.

### ISSUE THREAD

**Issue by harshitkeshrihk** [DSC-JSS-NOIDA/RapidHire#16]
Add fade animation.

![Contact](https://user-images.githubusercontent.com/85623292/193912062-b65acbdf-68c8-4b1d-a5f9-e96caba2caba.png)

Add this logo.

![Frame 3](https://user-images.githubusercontent.com/85623292/193912154-6820cd73-e358-4e60-89b8-6baa4f68c8ca.png)

**Comment by nandinivats30** [comment]
Assign me this issue.

**Comment by PratikAgrawal02** [comment]
Can you assign me this issue i want to update its UI

**Comment by PratikAgrawal02** [comment]
https://user-images.githubusercontent.com/99110383/194095276-ce2d8af1-1bc1-4ced-bec3-27757fb8a84f.mp4

**Comment by princegupta25** [comment]
@nandinivats30 gentle reminder, if you are not working on this issue. Please inform so that we can assign it to other contributor.
s

**Comment by princegupta25** [comment]
@nandinivats30 gentle reminder, if you are not working on this issue. Please inform so that we can assign it to other contributors.

**Comment by nandinivats30** [comment]
You can assign to other contributor.

**Comment by PratikAgrawal02** [comment]
Hello i have already sent a pull request please see it and merge the request.
