### ISSUE TITLE
Add logo in upload resume screen and its background gradient.

### ISSUE THREAD

**Issue by harshitkeshrihk** [DSC-JSS-NOIDA/RapidHire#35]
Add this logo in given screen and gradient background color.

![uploadresumelogo](https://user-images.githubusercontent.com/85623292/197847804-f1e14e7b-df43-4b7d-ae21-8b29bab9bc90.png)

![uploadresumescreen](https://user-images.githubusercontent.com/85623292/197847995-855dfba3-c446-4e7d-8d69-7e5041398c05.png)

**Comment by Georgezogos** [comment]
Hello, could you please assign it to me?
