### ISSUE TITLE
UI changes for AdminUserSelect Activity

### ISSUE THREAD

**Issue by harshitkeshrihk** [DSC-JSS-NOIDA/RapidHire#6]
Add Lift on touch animation in on click events of candidate and admin CardViews.

![Screenshot 2022-10-01 134321](https://user-images.githubusercontent.com/85623292/193399960-ebbd72b0-37d7-4afd-9669-da9df7208377.png)

https://user-images.githubusercontent.com/85623292/193402130-00d2526f-f364-45e4-985b-465d72e8f2aa.mp4

**Comment by nandinivats30** [comment]
I wanna resolve this issue .Please assign me.
