### ISSUE TITLE
UI changes for AdminRegisterScreen

### ISSUE THREAD

**Issue by harshitkeshrihk** [DSC-JSS-NOIDA/RapidHire#8]
Create layout file for admin register screen  and update its UI.

![AdminUserRegister](https://user-images.githubusercontent.com/85623292/193607597-a4ce98e2-cd1b-4f9c-962b-3e03713e3cb6.png)

**Comment by insfirred** [comment]
I want to work on this issue.

**Comment by priyanshusingh305** [comment]
Hi @harshitkeshrihk ,
I would like to work on this issue

**Comment by neil0504** [comment]
Hello @harshitkeshrihk , I would like to work on this issue if no one else is.

**Comment by harshitkeshrihk** [comment]
@insfirred reminder to complete this  issue..
